export const carModels = [
    {
        model: "Tesla CyberTruck",
        brand: "Tesla",
        pricePerDay: 199,
        color: "Gray",
        type: "SUV",
        transmission: "Automatic/Manual",
        image: require("../assets/TeslaCybertruck.png"),
    },
    {
        model: "Honda Civic",
        brand: "Honda",
        pricePerDay: 99,
        color: "White",
        type: "Compact",
        transmission: "Automatic/Manual",
        image: require("../assets/HondaCivic.png"),
    },
    {
        model: "Honda Vezel",
        brand: "Honda",
        pricePerDay: 89,
        color: "White",
        type: ["Compact", "SUV"], 
        transmission: "Automatic/Manual",
        image: require("../assets/HondaVezel.png"),
    },
    {
        model: "Honda Fit",
        brand: "Honda",
        pricePerDay: 69,
        color: "White",
        type: "Hatchback",
        transmission: "Automatic/Manual",
        image: require("../assets/HondaFit.png"),
    },
    {
        model: "Toyota Aqua",
        brand: "Toyota",
        pricePerDay: 69,
        color: "White",
        type: "Hatchback",
        transmission: "Automatic/Manual",
        image: require("../assets/ToyotaAqua.png"),
    },
    {
        model: "Tesla Model S",
        brand: "Tesla",
        pricePerDay: 159,
        color: "Red",
        type: "Executive",
        transmission: "Automatic/Manual",
        image: require("../assets/TeslaModelS.png"),
    },
    {
        model: "Ferrari 458",
        brand: "Ferrari",
        pricePerDay: 299,
        color: "Red",
        type: "Sports",
        transmission: "Manual",
        image: require("../assets/Ferrari458.png"),
    },
    {
        model: "Ford Mustang",
        brand: "Ford",
        pricePerDay: 159,
        color: "Blue",
        type: "Sports",
        transmission: "Manual",
        image: require("../assets/FordMustang.png"),
    },
];

export default {carModels};